### ISSUE TITLE
Create Wiki

### ISSUE THREAD

**Issue by Ndidi** [janm399/sbt-docbook-plugin#5]
I've a number of ideas for helping users with more advanced DocBook functionality, however the Readme is already bloated.. I think a Wiki is the way to go, however the 'Wiki' button that normally exists between 'Issues' and 'Stats & Graphs' is nowhere to be seen... @janm399, if you can see the button, could you please push it?

**Comment by janm399** [comment]
Done, you should now see the Wiki "button"
